# Generated by Django 6.0.5 on 2026-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(choices=[('preview_created', 'Preview created'), ('export_started', 'Export started'), ('export_completed', 'Export completed'), ('export_failed', 'Export failed')], max_length=64)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('theme', models.CharField(blank=True, max_length=32)),
                ('export_format', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['event_name', 'created_at'], name='codeshot_pr_event_n_952822_idx')],
            },
        ),
    ]
