# Generated by Django 6.0.5 on 2026-07-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeshot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productevent',
            options={'permissions': [('export_images', 'Can export images'), ('view_product_stats', 'Can view product statistics')]},
        ),
    ]
